# Generated by Django 4.0 on 2022-01-12 12:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Articles', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Category',
            new_name='ArticleCategory',
        ),
    ]
